name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: CI
    uses: silverstripe/gha-ci/.github/workflows/ci.yml@v1
    with:
      # require the following in ci.yml rather than composer.json require-dev specifically because unlike
      # regular modules, require-dev will get installed to projects during `composer create-project silverstripe/recipe-blog`
      composer_require_extra: silverstripe/frameworktest:^2
